name: ProjectML
channels: 
- conda-forge
- defaults
dependencies:
- python==3.8.5
- pandas
- pytest
- isort
- pre-commit
- flake8
- pip

- pyzmq
- ipykernel
- seaborn
-neptune-client==0.9.4
- Sklearn
- qgrid